dist: trusty
language: python

services:
  - postgresql

python:
  - '2.7'
  - '3.6'

addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-9.4-postgis-2.3

env:
  - GEOKEY='>=1.6,<1.7' DJANGO='>=1.11,<1.12' DEPLOY=0
  - GEOKEY='>=1.7,<1.8' DJANGO='>=1.11,<1.12' DEPLOY=1

virtualenv:
  system_site_packages: true

install:
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo apt-get install binutils libav-tools
  - sudo apt-get -yq install libgdal-dev python-gdal
  - gdal-config --version
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal

before_script:
  - psql template1 postgres -c 'create extension hstore;'
  - psql -c 'create database geokey;' -U postgres
  - psql -U postgres -d geokey -c 'create extension postgis;'
  - pip install geokey$GEOKEY
  - pip install django$DJANGO
  - python -c "import django; print('DJANGO %s ' % django.get_version())"
  - python -c "from geokey.version import get_version; print('GEOKEY %s' % get_version())"
  - pip install -r travis_ci/requirements.txt
  - pip install -e .
  - python travis_ci/manage.py migrate

script:
  - coverage run --source=geokey_epicollect travis_ci/manage.py test geokey_epicollect

after_success:
  - coveralls

deploy:
  provider: pypi
  user: excites
  password:
    secure: aoijikh3XtaaignvSp7N9VdFhqVCoLT7mpEbgeJE1NcL+AQr4EseqP6DZn9Yk/VxrU2G2Ufd53a1Twm4bQC+7r5ffvV/6s787SbIhFYQDkcAIJZjEnX+Qcxu8OBzNCQK0r0vX1z/yw5Ea4azuPcp/SeFaB4mrsu5TJfZ8xRtOzY=
  on:
    tags: true
    branch: master
    python: '3.6'
    condition: $DEPLOY = 1
